/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package camilo_medina.gitmanager.GUI;
import camilo_medina.gitmanager.execCommand.SelectDir;
import camilo_medina.gitmanager.DBAdmin.LeerComandos;
import camilo_medina.gitmanager.DBAdmin.ParametroInvalidoException;

/**
 *
 * @author Camilo Medina
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        TitleBar = new javax.swing.JPanel();
        DirLabel = new javax.swing.JLabel();
        DirectorioPathLabel = new javax.swing.JLabel();
        ContentBar = new javax.swing.JPanel();
        PanelComandos = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        SeleccionarDirectorioBoton = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BotonVerComandos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TitleBar.setBackground(new java.awt.Color(255, 255, 255));

        DirLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DirLabel.setForeground(new java.awt.Color(0, 0, 0));
        DirLabel.setText("Directorio:");

        DirectorioPathLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DirectorioPathLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout TitleBarLayout = new javax.swing.GroupLayout(TitleBar);
        TitleBar.setLayout(TitleBarLayout);
        TitleBarLayout.setHorizontalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(DirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DirectorioPathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        TitleBarLayout.setVerticalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DirectorioPathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirLabel))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        ContentBar.setBackground(new java.awt.Color(239, 240, 246));
        ContentBar.setPreferredSize(new java.awt.Dimension(1230, 620));

        PanelComandos.setBackground(new java.awt.Color(239, 240, 246));

        javax.swing.GroupLayout PanelComandosLayout = new javax.swing.GroupLayout(PanelComandos);
        PanelComandos.setLayout(PanelComandosLayout);
        PanelComandosLayout.setHorizontalGroup(
            PanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelComandosLayout.setVerticalGroup(
            PanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContentBarLayout = new javax.swing.GroupLayout(ContentBar);
        ContentBar.setLayout(ContentBarLayout);
        ContentBarLayout.setHorizontalGroup(
            ContentBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PanelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContentBarLayout.setVerticalGroup(
            ContentBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentBarLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(PanelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBar.setBackground(new java.awt.Color(0, 97, 247));

        SeleccionarDirectorioBoton.setBackground(new java.awt.Color(0, 97, 247));
        SeleccionarDirectorioBoton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeleccionarDirectorioBoton.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionarDirectorioBoton.setText("Seleccionar Directorio");
        SeleccionarDirectorioBoton.setBorder(null);
        SeleccionarDirectorioBoton.setContentAreaFilled(false);
        SeleccionarDirectorioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarDirectorioBotonMouseClicked(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Titulo.setText("Administrador de GIT gráfico");

        jSeparator1.setBackground(new java.awt.Color(239, 240, 246));
        jSeparator1.setForeground(new java.awt.Color(239, 240, 246));

        BotonVerComandos.setBackground(new java.awt.Color(0, 97, 247));
        BotonVerComandos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        BotonVerComandos.setForeground(new java.awt.Color(255, 255, 255));
        BotonVerComandos.setText("Ver Comandos");
        BotonVerComandos.setBorder(null);
        BotonVerComandos.setContentAreaFilled(false);
        BotonVerComandos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVerComandosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeleccionarDirectorioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Titulo)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(BotonVerComandos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(BotonVerComandos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                .addComponent(SeleccionarDirectorioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContentBar, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(TitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContentBar, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
            .addComponent(SideBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarDirectorioBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarDirectorioBotonMouseClicked
        // TODO add your handling code here:
        SelectDir.seleccion();
        String DirPath = SelectDir.getDirectorio();
        System.out.println(DirPath);
        DirectorioPathLabel.setText(DirPath);
    }//GEN-LAST:event_SeleccionarDirectorioBotonMouseClicked

    private void BotonVerComandosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerComandosMouseClicked
        PanelComandos.setVisible(true);
        LeerComandos Lector = new LeerComandos();
        try {
            String [][] comandos = Lector.ListarComandos();
            for(int i = 0; i < comandos.length; i++){
                for (int j = 0; j < 4; j++){
                    System.out.println(comandos[i][j]);
                }
            }
        } catch (ParametroInvalidoException ex) {
            System.out.println("Error" +
                               ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_BotonVerComandosMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BotonVerComandos;
    private javax.swing.JPanel ContentBar;
    private javax.swing.JLabel DirLabel;
    private javax.swing.JLabel DirectorioPathLabel;
    private javax.swing.JPanel PanelComandos;
    private javax.swing.JButton SeleccionarDirectorioBoton;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel TitleBar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
